# Example configuration file
name: example-config
version: "1.0"
description: Example configuration for embedded content demos

settings:
  timeout: 30s
  retries: 3
  parallel: true

hosts:
  - name: localhost
    type: local
  - name: example.com
    type: ssh
    port: 22

modules:
  - file
  - service
  - package